name: 'Release'

on:
  push:
    tags: ['*']

permissions:
  contents: 'write'

jobs:
  release:
    uses: zenhelix/ci-workflows/.github/workflows/gradle-plugin-release.yml@v3
    with:
      java-version: '17'
      publish-command: './gradlew publishPlugins publish -Pversion=''${{ github.ref_name }}'''
    secrets: inherit
